# .streamlit/config.toml

[theme]
base = "dark"
primaryColor = "#4C7364"  # vert doux
backgroundColor = "#070D0C"  # noir profond
secondaryBackgroundColor = "#1F2A25"  # vert très sombre
textColor = "#D9CCA7"  # beige clair, très lisible

[server]
maxUploadSize = 1024

# Les couleurs du logo :
#    Noir : #070D0C
#    Vert : #4C7364
#    Beige clair : #D9CCA7
#    Marron foncé : #594A2D
#    Marron clair : #BFB093